export const CHILDRENTIPS_SUCCESSFULLY_REGISTERED = 'CHILDRENTIPS_SUCCESSFULLY_REGISTERED';
export const REGISTERING_CHILDRENTIPS_FAILED = 'REGISTERING_CHILDRENTIPS_FAILED';


export const REGISTERED_CHILDRENTIPS_FETCHED_SUCCESSFULLY = 'REGISTERED_CHILDRENTIPS_FETCHED_SUCCESSFULLY';
export const REGISTERED_CHILDRENTIPS_EMPTY_RESULTS = 'REGISTERED_CHILDRENTIPS_EMPTY_RESULTS';
export const ERROR_FETCHING_CHILDRENTIPS = 'ERROR_FETCHING_CHILDRENTIPS';



