export const SYSTEM_ADMIN_SUCCESSFULLY_REGISTERED = 'SYSTEM_ADMIN_SUCCESSFULLY_REGISTERED';
export const REGISTERING_SYSTEM_ADMIN_FAILED = 'REGISTERING_SYSTEM_ADMIN_FAILED';


export const REGISTERED_SYSTEM_ADMIN_FETCHED_SUCCESSFULLY = 'REGISTERED_SYSTEM_ADMIN_FETCHED_SUCCESSFULLY';
export const REGISTERED_SYSTEM_ADMIN_EMPTY_RESULTS = 'REGISTERED_SYSTEM_ADMIN_EMPTY_RESULTS';
export const ERROR_FETCHING_SYSTEM_ADMIN = 'ERROR_FETCHING_SYSTEM_ADMIN';



